version: "3.8"
services:
   mongodb:
    container_name: mongo
    image: mongo:latest
    volumes:
      - ./backend/data:/Test123
    ports:
      - "27017:27017"
    
   backend:
    container_name: backend
    build:
     context: ./backend
    env_file:
     - ./backend/.env.sample
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

   frontend:
    container_name: frontend
    build:
     context: ./frontend
    env_file:
     - ./backend/.env.sample
    ports:
      - "5173:5173" 
   
volumes:
  Test123:
